const PDFDocument = require('pdfkit');

/**
 * Convert plain text AI response into a formatted PDF buffer.
 * Returns a Promise<Buffer> — upload this directly to S3.
 */
const generatePDF = (text, type = 'resume', userName = '') => {
  return new Promise((resolve, reject) => {
    const doc    = new PDFDocument({ margin: 50, size: 'A4' });
    const chunks = [];

    doc.on('data',  (chunk) => chunks.push(chunk));
    doc.on('end',   ()      => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);

    // ── Header bar ───────────────────────────────────────────────────
    doc.rect(0, 0, doc.page.width, 8).fill('#e07d15');

    // ── Logo / App name ──────────────────────────────────────────────
    doc.moveDown(0.5);
    doc
      .font('Helvetica-Bold')
      .fontSize(10)
      .fillColor('#e07d15')
      .text('VitaCraft AI', 50, 25);

    doc
      .font('Helvetica')
      .fontSize(8)
      .fillColor('#888888')
      .text(`Generated on ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}`, { align: 'right' });

    doc.moveDown(1);

    // ── Document title ───────────────────────────────────────────────
    const titleMap = {
      resume:       'Professional Resume',
      cover_letter: 'Cover Letter',
      job_analysis: 'Job Description Analysis',
    };

    doc
      .font('Helvetica-Bold')
      .fontSize(20)
      .fillColor('#1a1a2e')
      .text(titleMap[type] || 'Document', { align: 'center' });

    if (userName) {
      doc
        .font('Helvetica')
        .fontSize(13)
        .fillColor('#555555')
        .text(userName, { align: 'center' });
    }

    doc.moveDown(0.5);

    // ── Divider line ─────────────────────────────────────────────────
    doc
      .moveTo(50, doc.y)
      .lineTo(doc.page.width - 50, doc.y)
      .strokeColor('#e07d15')
      .lineWidth(1.5)
      .stroke();

    doc.moveDown(1);

    // ── Content — parse sections from AI output ───────────────────────
    const lines = text.split('\n');

    lines.forEach((line) => {
      const trimmed = line.trim();
      if (!trimmed) { doc.moveDown(0.4); return; }

      // Section headers (ALL CAPS or ends with colon)
      if (
        /^[A-Z\s]{4,}$/.test(trimmed) ||
        /^(SUMMARY|EXPERIENCE|EDUCATION|SKILLS|OBJECTIVE|CERTIFICATIONS|PROJECTS|REFERENCES|WORK HISTORY)/i.test(trimmed)
      ) {
        doc.moveDown(0.6);
        doc
          .font('Helvetica-Bold')
          .fontSize(12)
          .fillColor('#e07d15')
          .text(trimmed.toUpperCase());

        // Underline
        const textWidth = doc.widthOfString(trimmed.toUpperCase());
        doc
          .moveTo(50, doc.y)
          .lineTo(50 + Math.min(textWidth + 10, doc.page.width - 100), doc.y)
          .strokeColor('#e07d15')
          .lineWidth(0.5)
          .stroke();

        doc.moveDown(0.3);
        return;
      }

      // Bullet points
      if (trimmed.startsWith('•') || trimmed.startsWith('-') || trimmed.startsWith('*')) {
        doc
          .font('Helvetica')
          .fontSize(10)
          .fillColor('#333333')
          .text(`• ${trimmed.replace(/^[•\-\*]\s*/, '')}`, {
            indent: 15,
            lineGap: 2,
          });
        return;
      }

      // Bold lines (job titles, company names — lines in Title Case)
      if (/^[A-Z][a-zA-Z\s,|–-]{5,}$/.test(trimmed) && trimmed.length < 80) {
        doc
          .font('Helvetica-Bold')
          .fontSize(10)
          .fillColor('#222222')
          .text(trimmed);
        return;
      }

      // Regular text
      doc
        .font('Helvetica')
        .fontSize(10)
        .fillColor('#333333')
        .text(trimmed, { lineGap: 2 });
    });

    // ── Footer ────────────────────────────────────────────────────────
    const pageHeight = doc.page.height;
    doc
      .rect(0, pageHeight - 30, doc.page.width, 30)
      .fill('#f8f4f0');

    doc
      .font('Helvetica')
      .fontSize(7)
      .fillColor('#aaaaaa')
      .text(
        'Generated by VitaCraft AI  •  vitacraft.ai  •  For personal use only',
        0, pageHeight - 20,
        { align: 'center' }
      );

    doc.end();
  });
};

module.exports = { generatePDF };